#!/usr/bin/env python3
"""Regenerate README.md from systems/*.yaml.

Usage: python scripts/build_readme.py
"""
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

HEADER = """\
# S3D Taxonomy

A community-maintained taxonomy of deployed and research security and privacy systems,
mapped to [Hoepman's eight privacy design strategies](https://www.cs.ru.nl/~jhh/publications/pdp.pdf)
and the [OECD Fair Information Practice Principles](https://www.oecd.org/en/publications/oecd-guidelines-on-the-protection-of-privacy-and-transborder-flows-of-personal-data_9789264196391-en.html).
Sources are drawn primarily from PETS/PoPETs and PEPR proceedings and industry
engineering blogs, since privacy-enhancing technology is where security-based
system design is most thoroughly documented.

Each system lives in one YAML file under [`systems/`](systems/), validated against
[`schema/system.schema.json`](schema/system.schema.json). See
[CONTRIBUTING.md](CONTRIBUTING.md) to add or improve an entry.

**Hoepman strategies:** minimise, hide, separate, abstract, inform, control, enforce, demonstrate
**OECD principles:** collection limitation, data quality, purpose specification, use limitation,
security safeguards, openness, individual participation, accountability

## Using this repo as a database

The YAML files are compiled into machine-readable formats in [`data/`](data/):

- **`data/systems.json`** — the full dataset as a JSON array
- **`data/index.json`** — system ids grouped by strategy, principle, technology, technique, developer, and status
- **`data/systems.db`** — SQLite database with `systems`, `hoepman`, `oecd`, `technologies`, and `techniques` tables

Fetch the JSON directly from GitHub:

```bash
curl -s https://raw.githubusercontent.com/slim2134/s3d_taxonomy/main/data/systems.json \\
  | jq '.[] | select(.hoepman[]?.strategy == "demonstrate") | .name'
```

Or query with SQL:

```bash
sqlite3 data/systems.db "SELECT name, developer FROM systems s
  JOIN technologies t ON t.system_id = s.id
  WHERE t.technology = 'trusted-execution-environment';"
```

Or in Python:

```python
import json, urllib.request
url = "https://raw.githubusercontent.com/slim2134/s3d_taxonomy/main/data/systems.json"
systems = json.load(urllib.request.urlopen(url))
deployed_dp = [s["name"] for s in systems if s["status"] == "deployed"
               and any("differential-privacy" in t for t in s["technologies"])]
```

## Credits

Created and maintained by **Sean Lim** (Carnegie Mellon University).

- **Eva Li** — contributor
- **Dr. Hana Habib** (Carnegie Mellon University) — faculty advisor

Community contributions are welcome — see [CONTRIBUTING.md](CONTRIBUTING.md).
Contributors are recognized through the repository's commit history and pull requests.

*This file is auto-generated by `scripts/build_readme.py`. Do not edit the tables by hand.*
"""


def load():
    systems = []
    for path in sorted((ROOT / "systems").glob("*.yaml")):
        doc = yaml.safe_load(path.read_text())
        doc["_file"] = path.name
        systems.append(doc)
    return systems


def esc(s):
    return (s or "").replace("|", "\\|").replace("\n", " ")


def link(doc):
    name = esc(doc["name"])
    return f"[{name}](systems/{doc['_file']})"


def main():
    systems = load()
    complete = [s for s in systems if s.get("analysis_status") == "complete"]
    stubs = [s for s in systems if s.get("analysis_status") != "complete"]

    lines = [HEADER]
    lines.append(f"\n## Analyzed systems ({len(complete)})\n")
    lines.append("| System | Developer | Status | Hoepman | OECD |")
    lines.append("|---|---|---|---|---|")
    for s in sorted(complete, key=lambda x: (str(x.get("developer") or "~"), x["name"])):
        hoep = ", ".join(h["strategy"] for h in s.get("hoepman", []))
        oecd = ", ".join(o["principle"] for o in s.get("oecd", []))
        lines.append(
            f"| {link(s)} | {esc(s.get('developer'))} | {s.get('status', '')} | {hoep} | {oecd} |"
        )

    lines.append(f"\n## Awaiting analysis ({len(stubs)}) — contributions welcome\n")
    lines.append("| System | Developer | Source |")
    lines.append("|---|---|---|")
    for s in sorted(stubs, key=lambda x: (str(x.get("developer") or "~"), x["name"])):
        src = f"[link]({s['source']})" if s.get("source") else ""
        lines.append(f"| {link(s)} | {esc(s.get('developer'))} | {src} |")

    lines.append("\n## Strategy coverage\n")
    lines.append("| Hoepman strategy | Systems |")
    lines.append("|---|---|")
    strategies = ["minimise", "hide", "separate", "abstract", "inform", "control", "enforce", "demonstrate"]
    for strat in strategies:
        names = [esc(s["name"]) for s in complete if any(h["strategy"] == strat for h in s.get("hoepman", []))]
        lines.append(f"| {strat} | {', '.join(names)} |")

    (ROOT / "README.md").write_text("\n".join(lines) + "\n")
    print(f"README.md written: {len(complete)} analyzed, {len(stubs)} stubs.")


if __name__ == "__main__":
    main()
